//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marcom_Application.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class master_employee
    {
        public int id { get; set; }
        public string employee_number { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> m_company_id { get; set; }
        public string email { get; set; }
        public bool is_delete { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
